# Generated by Django 5.2.16 on 2026-07-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttoken',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
